esphome:
  name: pn532-ndef-test
  friendly_name: PN532 NDEF Test

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: VERY_VERBOSE
  hardware_uart: USB_SERIAL_JTAG

external_components:
  - source:
      type: local
      path: components
    components: [pn532, pn532_spi, pn532_i2c]
    refresh: 0s

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 400kHz

pn532_i2c:
  id: pn532_board
  address: 0x24
  update_interval: 2s
  on_tag:
    then:
      - logger.log:
          format: "Tag detected: %s"
          args: ['x.c_str()']

binary_sensor:
  - platform: pn532
    pn532_id: pn532_board
    name: "Mifare Classic Tag"
    uid: "DE-A3-0D-00"
